### ISSUE TITLE
inferExp step fails with mixed protocol BAM file

### ISSUE THREAD

**Issue by emi80** [guigolab/grape-nf#71]
```
Reading reference gene model genomic.bed ... Done
Loading SAM/BAM file ...  Finished
Total 0 usable reads were sampled
------ STATS ------
Protocol: Mixture
Traceback (most recent call last):
  File "/users/rg/avlot/.nextflow/assets/guigolab/grape-nf/bin/grape_infer_experiment.py", line 124, in <module>
    main()
  File "/users/rg/avlot/.nextflow/assets/guigolab/grape-nf/bin/grape_infer_experiment.py", line 118, in main
    print >>sys.stderr, 'Fraction of reads explained by other combinations: %.4f' % other
TypeError: float argument required, not str
```

**Comment by emi80** [comment]
this may happen when there are no mapped reads in the BAM 
file
